<?php
$x = mysql_connect("localhost","root","123");
//mysql_query("CREATE DATABASE saude") or die (mysql_error());
mysql_query("CREATE TABLE saude.cliente(
  idcliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(30) NULL,
  data_nasc DATE NULL,
  mae VARCHAR(30) NULL,
  pai VARCHAR(30) NULL,
  rg VARCHAR(15) NULL,
  exp VARCHAR(30) NULL,
  sexo VARCHAR(1) NULL,
  etnia VARCHAR(30) NULL,
  estado_civil VARCHAR(30) NULL,
  proff_atual VARCHAR(30) NULL,
  proff_anterior VARCHAR(30) NULL,
  endereco_res VARCHAR(30) NULL,
  n_res INT(5) NULL,
  bairro_res VARCHAR(30) NULL,
  endereco_pro VARCHAR(30) NULL,
  n_pro VARCHAR(30) NULL,
  bairro_pro VARCHAR(30) NULL,
  tel VARCHAR(13) NULL,
  tel_pro VARCHAR(13) NULL,
  cel VARCHAR(13) NULL,
  contato VARCHAR(30) NULL,
  demanda VARCHAR(30) NULL,
  indicado VARCHAR(30) NULL,
  queixa TEXT NULL,
  hist_doenca TEXT NULL,
  inter_hosp TEXT NULL,
  hist_familia TEXT NULL,
  hist_pessoal TEXT NULL,
  hist_escolar TEXT NULL,
  hist_ocu TEXT NULL,
  habitos TEXT NULL,
  revisao TEXT NULL,
  ecto TEXT NULL,
  exame_sis TEXT NULL,
  exame_neu TEXT NULL,
  aparencia TEXT NULL,
  atitude TEXT NULL,
  consciencia TEXT NULL,
  orientacao TEXT NULL,
  atencao TEXT NULL,
  memoria TEXT NULL,
  senso TEXT NULL,
  pensamento TEXT NULL,
  linguagem TEXT NULL,
  inteligencia TEXT NULL,
  do_eu TEXT NULL,
  humor TEXT NULL,
  afeto TEXT NULL,
  volicaco TEXT NULL,
  psi TEXT NULL,
  insight TEXT NULL,
  contratrans TEXT NULL,
  sumula TEXT NULL,
  diagnostico TEXT NULL,
  cid TEXT NULL,
  dsm TEXT NULL,
  exames_compl TEXT NULL,
  cadastrar TEXT NULL,
  PRIMARY KEY(idcliente)
)engine=InnoDB;")or die (mysql_error());
mysql_close($x)



?>

